name: GitHub Actions
run-name: ${{ github.actor }} merge to TEST ğŸš€
on:
  push:
    branches:
      - test
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: Get the latest tag
        id: get_tag
        run: |
          # Get the latest tag
          LATEST_TAG=$(git tag -l | tail -1)
          # Output the tag for use in other steps
          echo "latest-tag=$LATEST_TAG" >> "$GITHUB_OUTPUT"
      - name: Using the latest tag
        run: |
          # Access the latest tag
          echo "The latest tag is ${{ steps.get_tag.outputs.latest-tag }}"
      - run: echo "ğŸ This job's status is ${{ job.status }}."
